ECP<-read.table("household_power_consumption.txt",sep=";",header=TRUE,na.strings="?",colClasses = c("character", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
ECP$Date=strptime(paste(ECP$Date,ECP$Time),"%d/%m/%Y %H:%M:%S")
ECP1=subset(ECP,(ECP$Date>=strptime("2007-02-01","%Y-%m-%d")&(ECP$Date<strptime("2007-02-02","%Y-%m-%d"))))
library(datasets)
png(filename="plot3.png",width=480,height=480,bg="white")
plot(ECP1$Date, ECP1$Sub_metering_1,type="l",col="black",xlab="",ylab="Energy Sub metering")
lines(ECP1$Date, ECP1$Sub_metering_2,col="red")
lines(ECP1$Date, ECP1$Sub_metering_3,col="blue")
legend("topright",lwd=1,c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"))
dev.off()
